### ISSUE TITLE
Story Map

### ISSUE THREAD

**Issue by kwritenow** [chihacknight/il-budget-clock#1]
# Story map 01/21/16

To view it in larger format, view online in Boardthing as a guest: http://boardthing.com/board/569d462cbf753be800000630
![il budget clock](https://cloud.githubusercontent.com/assets/14225940/12486787/c6048840-c029-11e5-945b-c19f85aad719.png)

**Comment by kwritenow** [comment]
Given the urgency, we might want to skip testing the paper prototype with users and just use it internally. We could interview and test using the first release.

**Comment by cathydeng** [comment]
agreed. for this project, I think timeliness matters a lot, and getting something out the door quickly is going to be more effective than creating something w/ lotsa features that takes a long time. I think there's a lot of value in keeping projects small & doing one small thing well, especially since many hack night projects are long term. also this is partially selfish because I don't have the time to work on a large project :stuck_out_tongue: 

for this project, I'm thinking we implement the clock and one other thing (explaining background or highlighting orgs impacted, etc). I'd say the first planning step would be to decide what that other thing is. a lot of these other notes are great ideas, and could be spun off into individual small projects!

**Comment by kwritenow** [comment]
I did include everything that got mentioned and unpacked those items a bit in the story map, with the intention of putting them in a backlog, unless we discovered they were more important than they seemed.

OK, so it's helpful to know what would fit into your schedule. I can do some quick sketches this weekend, most likely. 

Unless others really want to be involved in that, in which case, let's try to set up a skype session.

**Comment by cathydeng** [comment]
I don't think we're at a stage to have sketches yet, although one thing that would be very helpful to do beforehand would be some research on the budget crisis itself - that's gona be the most time consuming part of this imo, & the main bottleneck. I'd like to whip together a complete website with a clock & some content next tuesday (do-able on my end), & then maybe spend some more time polishing the tuesday after & launch! I'd prefer this to not go beyond 2 weeks.

**Comment by hunterowens** [comment]
Closing for now. We can refer back to this if we decide to do a full scale campaign.
