### ISSUE TITLE
why does this matter?

### ISSUE THREAD

**Issue by cathydeng** [chihacknight/il-budget-clock#15]
related to #11 

would be good to have a bunch of clear, polished one sentence answers to the question 'why does this matter?' 

I think this is a clear framing & we can post a bunch of reasons on the site, and also collect answers to this question on the site (related to kristi's idea in #13).

list 'em here!

**Comment by kwritenow** [comment]
Because some organizations that provide services to citizens in need can't operate without state funds.

When we finally get a budget, some of the organizations that provide services to citizens in need will have shut down permanently.

Because it damages the State's credit rating.

Because our lawmakers are failing at a fundamental part of their job--they're letting extreme ideology grind government functions to a halt.

Because lawmakers are demonstrating they are willing to let people suffer for the sake of ideology.

Because the result of this political strongarming is that our most vulnerable citizens are losing critical services.

**Comment by hunterowens** [comment]
Because we might turn off the lights at government offices. Literally. [Source](http://www.chicagotribune.com/news/local/politics/ct-jesse-white-illinois-budget-met-0926-20150925-story.html) 

Because Medicaid patients might stop receiving healthcare. [Source](http://progressillinois.com/news/content/2015/07/23/state-hit-suit-over-hospital-medicaid-payments-during-budget-impasse)

Because 5,000 Chicago Public School Teachers might loose their jobs. [Source](http://chicago.suntimes.com/chicago-politics/7/71/972395/claypool-many-5000-chicago-public-school-teachers-face-november-layoff)

**Comment by cathydeng** [comment]
these are excellent, thx @kwritenow & @hunterowens!! keep 'em coming :grin:

**Comment by hunterowens** [comment]
Ok. We've got a dozen or so in there for now, so closing this issue. We can always add, but I'd like to get something up ASAP.

**Comment by cathydeng** [comment]
let's keep this issue open for new folks who wana help, since it's an easy way for anyone to get involved in this project. we could have a couple people on this task tomorrow

**Comment by hunterowens** [comment]
Ok, sounds good.

**Comment by kwritenow** [comment]
I've posted site copy and reasons for collaboration here: https://docs.google.com/document/d/1oM6i2YEhFO2x3nMmUUsSatY9-_dDowVCS3JvM4T7F7Y/edit?usp=sharing

I left out the 5K teachers reason because that issue has progressed since the above article was posted in Sept. Plus, that political water is murky. It would be nice to have a statement there that is focused enough to be traced mostly back to the budget crisis.

I left out reasons from my original list above because they are abstract and wordy and unsourced.

**Comment by kwritenow** [comment]
Maybe after the user sees a certain number of reasons, the call to action gets focus automatically. Or they see a link to our twitter account to see more reasons.

Is there a way that adding reasons to a google form could populate a reason on the site AND send a tweet? Fields: Reason text, source URL, link text

**Comment by cathydeng** [comment]
I wouldn't want to populate anything automatically, b/c any free input in the internet will probably require some moderation. I'd love to have a google form with very structured input (e.g. share why this matters to you, personal story or source if available) & then manually add the valid ones to the site

**Comment by kwritenow** [comment]
Yes, i was suggesting this for internal use, not for the "tell us your story" idea. That will def need moderation.

**Comment by hunterowens** [comment]
:fireworks: Nice job @chihacknight/il-budget-clock team!
