### ISSUE TITLE
Content on why the budget crisis exists

### ISSUE THREAD

**Issue by cathydeng** [chihacknight/il-budget-clock#9]
what the two sides are fighting for, background, etc

drop links here

**Comment by kwritenow** [comment]
Site blurb: (once we know our CTA, let's decide how it will stack in mobile and how much scrolling is OK)
My current thought is to call out legislators for being cavalier with social services and refusing to compromise. "Governor Rauner and the General Assembly are playing chicken with the lives of our most vulnerable citizens."

Social media blurb: (70-100 characters)

Social media image:
image of the clock, or protest signs, or closed facilities

 "Twitter’s in-stream preview is always 440 pixels wide and 220 pixels tall (a 2:1 ratio)." So: "Creating and calculating the dimensions of an image that will perfectly show off the center of the photo in the in-stream preview is very tricky.  We recommend creating 880×440 images to tweet.

One shortcut I’ve found is using the Facebook dimension (1200×627) on Twitter as well. While these images are not exactly a 2:1 image ratio, they still look great in Twitter’s in-stream preview and save you time!" http://blogs.constantcontact.com/social-media-image-sizes/

**Comment by kwritenow** [comment]
[Budget Clock]
since Illinois had a budget.
<a href=""> Learn more.</a>

<h2>So What?</h2>

Why does it matter? 

Because we might turn off the lights at government offices. <a href="http://www.chicagotribune.com/news/local/politics/ct-jesse-white-illinois-budget-met-0926-20150925-story.html">Literally.</a>

Because Medicaid patients <a href="http://progressillinois.com/news/content/2015/07/23/state-hit-suit-over-hospital-medicaid-payments-during-budget-impasse">might stop receiving healthcare.</a> 

Because 5,000 Chicago Public School teachers <a href="http://chicago.suntimes.com/news/7/71/1271192/rahm-gov-name-calling-doesnt-help">might loose their jobs.</a>

<h2>What can you do?</h2>

<h3>Call the people who are supposed to be getting this done.</h3>

Tell them this isn't acceptable. Without pressure from us, they aren't treating this as an urgent problem.

Call Governor Rauner: (217) 782-0244

Call  Speaker Madison: (217) 782-5350

Call your representatives in the General Assembly [lookup button or link]

<h3>Share this page.</h3>

[share buttons]

<h3>Tell us your story.</h3>

Have you lost services because of the

**Comment by cathydeng** [comment]
added to the about page
